### ISSUE TITLE
serialize encrypted data!

### ISSUE THREAD

**Issue by Mor4eza** [spxrogers/Alamofire-Gloss#12] opened 2017-08-08 14:50 UTC
hi
i get my data from our server as aes encrypted json.
how i can use your class to serialize encrypted data?
i can decrypt my data to normal json,bot how i can send my data after deycrypt them?!

sorry for bad english :(

Log:
`Response serialization failed: JSON could not be serialized because of error:
The operation couldn’t be completed. (Alamofire+Gloss error -1.)
Failure Reason: jsonSerializationFailed(Error Domain=Alamofire+Gloss Code=-1 "(null)" `

and part of code:

` Alamofire.request(request)
   
            .validate(statusCode: 200 ..< 300)
            .responseObject(T.self) { (response) in
                switch response.result {
                case .success(let response):
                    
                    completion(response, nil)
                case .failure(let error):
                    print("Error'd: \(error)")`

**Comment by spxrogers** [comment] 2017-08-10 22:56
hi @Mor4eza—

at the heart of it, the core serialization is done by Swfit's native [`JSONSerialization.jsonObject`](https://developer.apple.com/documentation/foundation/jsonserialization/1415493-jsonobject). if your JSON can be serialized via that native method, you should be fine as well. #11 is tracking an enhancement to bubble up the root cause of the serialization error, right now it is opaque to the calling user unfortunately.

edit: the line where `jsonObject` is called is [[here]](https://github.com/spxrogers/Alamofire-Gloss/blob/master/Source/Alamofire%2BGloss.swift#L154)

**Comment by spxrogers** [comment] 2017-09-13 01:52
closing this with the release of [2.1.0](https://github.com/spxrogers/Alamofire-Gloss/blob/master/CHANGELOG.md#210) that will help examine the root cause of your errors.

if you debug and find an issue with `Moya-Gloss`, please open up a new issue. thank you @Mor4eza!

**Closed as completed by spxrogers** 2017-09-13 01:52 UTC
